#pragma once

// Generated by CoMMALab/cricket gpu-cc-early-exit at commit
// 98582c35d81c6ed0d8c4badb7fdf78327523524c, then validated and namespaced by
// resources/ffw_sg2/postprocess_cricket_single_header.py.

namespace ppln::collision {





#define FFW_SG2_SINGLE_APPROX_SPHERE_COUNT 27
#define FFW_SG2_SINGLE_APPROX_JOINT_COUNT 9
#define FFW_SG2_SINGLE_APPROX_SELF_CC_RANGE_COUNT 26
#define FFW_SG2_SINGLE_FIXED -1
#define FFW_SG2_SINGLE_X_PRISM 0
#define FFW_SG2_SINGLE_Y_PRISM 1
#define FFW_SG2_SINGLE_Z_PRISM 2
#define FFW_SG2_SINGLE_X_ROT 3
#define FFW_SG2_SINGLE_Y_ROT 4
#define FFW_SG2_SINGLE_Z_ROT 5
#define FFW_SG2_SINGLE_BATCH_SIZE 16
#define FFW_SG2_SINGLE_JOINT_FLAG_STRIDE 9
#define FFW_SG2_SINGLE_TRANSFORM_SLOTS 1

__device__ __constant__ float4 ffw_sg2_single_approx_spheres_array[27] = {
    { -0.136f, 0.0f, 1.027f, 0.553001f },
    { 0.0105f, 0.002f, -0.106f, 0.202462f },
    { 0.003625f, 0.220375f, -0.0035f, 0.078549f },
    { -0.001f, 0.228f, -0.143705f, 0.086515f },
    { 0.025695f, 0.233195f, -0.285195f, 0.071988f },
    { -0.002496f, 0.2355f, -0.424435f, 0.078707f },
    { -0.0035f, 0.236f, -0.54656f, 0.063299f },
    { 0.0075f, 0.251f, -0.622f, 0.062492f },
    { 0.0465f, 0.2275f, -0.6955f, 0.093331f },
    { 0.0f, 0.2285f, -0.754f, 0.041007f },
    { 0.0f, 0.1825f, -0.7745f, 0.020001f },
    { 0.0f, 0.167137f, -0.829f, 0.020001f },
    { 0.0f, 0.2715f, -0.7715f, 0.020001f },
    { 0.0f, 0.288863f, -0.828f, 0.020001f },
    { 0.007f, -0.1005f, -0.001f, 0.08357f },
    { 0.0005f, 0.0f, -0.1415f, 0.090503f },
    { 0.0255f, -0.0045f, -0.116f, 0.074243f },
    { -0.041f, -0.015f, -0.1255f, 0.09077f },
    { 0.0f, -0.012f, -0.1025f, 0.067006f },
    { 0.008f, -0.0255f, -0.0705f, 0.063938f },
    { 0.0425f, 0.0f, -0.058f, 0.096918f },
    { 0.0f, 0.002f, -0.115f, 0.041025f },
    { 0.0f, -0.041f, -0.126f, 0.020001f },
    { 0.0f, -0.064363f, -0.1835f, 0.020001f },
    { 0.0f, 0.042f, -0.127f, 0.020001f },
    { 0.0f, 0.054363f, -0.1855f, 0.020001f },
    { 0.070057f, 0.0055f, 0.140003f, 0.123371f }
};

__device__ __constant__ float ffw_sg2_single_approx_fixed_transforms[] = {
    // joint 0
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 1
    1.0, 0.0, 0.0, -0.0199,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 1.4316,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 2
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, -0.1045,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 3
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, -0.123,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 4
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.165,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 5
    1.0, 0.0, 0.0, 0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.135,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 6
    1.0, 0.0, 0.0, -0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1489,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 7
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1041,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 8
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.0885,
    0.0, 0.0, 0.0, 1.0,
    
    
};

__device__ __constant__ int ffw_sg2_single_approx_sphere_to_joint[27] = {
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    8,
    8,
    8,
    8,
    8,
    1
};

__device__ __constant__ int ffw_sg2_single_approx_flattened_joint_to_spheres[36] = {
    0,
    -1,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    26,
    -1,
    14,
    -1,
    15,
    -1,
    16,
    -1,
    17,
    -1,
    18,
    -1,
    19,
    -1,
    20,
    21,
    22,
    23,
    24,
    25,
    -1
};

__device__ __constant__ int ffw_sg2_single_approx_joint_types[] = {
    3,
    2,
    4,
    3,
    5,
    4,
    5,
    4,
    3
};

__device__ __constant__ int ffw_sg2_single_approx_self_cc_ranges[26][3] = {
    { 0, 2, 26 },
    { 1, 15, 25 },
    { 2, 14, 25 },
    { 3, 14, 25 },
    { 4, 14, 25 },
    { 5, 14, 25 },
    { 6, 14, 25 },
    { 7, 14, 25 },
    { 8, 14, 25 },
    { 9, 14, 25 },
    { 10, 14, 25 },
    { 11, 14, 25 },
    { 12, 14, 25 },
    { 13, 14, 25 },
    { 14, 16, 26 },
    { 15, 17, 26 },
    { 16, 18, 26 },
    { 17, 19, 26 },
    { 18, 20, 26 },
    { 19, 21, 26 },
    { 20, 26, 26 },
    { 21, 26, 26 },
    { 22, 26, 26 },
    { 23, 26, 26 },
    { 24, 26, 26 },
    { 25, 26, 26 }
};

__device__ __constant__ int ffw_sg2_single_approx_joint_parents[9] = {
    0,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7
};

__device__ __constant__ int ffw_sg2_single_approx_T_memory_idx[9] = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
};

__device__ __constant__ int ffw_sg2_single_approx_dfs_order[9] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8
};

__device__ __constant__ int ffw_sg2_single_approx_joint_id_to_dof[9] = {
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7
};

template <>
__device__ void fk_approx<ppln::robots::FfwSg2Single>(
    const float* q,
    volatile float* sphere_pos_approx, // 27 spheres x 16 robots x 3 coordinates (each column is a robot)
    float *T, // 16 robots x 1 x 4x4 transform matrix , column major
    const int tid
)
{
    // every 4 threads are responsible for one column of the transform matrix T
    // make_transform will calculate the necessary column of T_step needed for the thread
    const int col_ind = tid % 4;
    const int batch_ind = tid / 4;

    int T_offset = batch_ind * 1 * 16;
    float T_step_col[4]; // 4x1 column of the joint transform matrix for this thread
    float *T_base = T + T_offset; // 4x4 transform matrix for the batch
    
    #pragma unroll
    for (int i = 0; i < 1; ++i) {
        float *T_col_i = T_base + i * 16 + col_ind * 4;
        for (int r=0; r<4; r++) {
            T_col_i[r] = 0.0f;
        }
        T_col_i[col_ind] = 1.0f;
    }
    __syncthreads();

    int joint_to_sphere_ind = 0;

    for (int j = 0; j < FFW_SG2_SINGLE_APPROX_JOINT_COUNT; ++j) {
        int i = ffw_sg2_single_approx_dfs_order[j];
        float T_col_tmp[4];
        int parent_idx = ffw_sg2_single_approx_joint_parents[i];
        int T_memory_idx_parent = ffw_sg2_single_approx_T_memory_idx[parent_idx];
        int T_memory_idx = ffw_sg2_single_approx_T_memory_idx[i];
        int q_idx = ffw_sg2_single_approx_joint_id_to_dof[i];
        if (j > 0) {
            int ft_addr_start = i * 16;
            int joint_type = ffw_sg2_single_approx_joint_types[i];

            if (joint_type <= FFW_SG2_SINGLE_Z_PRISM) {
                prism_fn(&ffw_sg2_single_approx_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col, joint_type);
            }
            else if (joint_type == FFW_SG2_SINGLE_X_ROT) {
                xrot_fn(&ffw_sg2_single_approx_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            else if (joint_type == FFW_SG2_SINGLE_Y_ROT) {
                yrot_fn(&ffw_sg2_single_approx_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            else if (joint_type == FFW_SG2_SINGLE_Z_ROT) {
                zrot_fn(&ffw_sg2_single_approx_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            
            for (int r=0; r<4; r++){
                T_col_tmp[r] = dot4_col(&T_base[T_memory_idx_parent*16 + r], T_step_col);
            }
            for (int r=0; r<4; r++){
                T_base[T_memory_idx*16 + col_ind*4 + r] = T_col_tmp[r];
            }
        }
        __syncwarp();
        while (ffw_sg2_single_approx_flattened_joint_to_spheres[joint_to_sphere_ind] != -1) {
            int sphere_ind = ffw_sg2_single_approx_flattened_joint_to_spheres[joint_to_sphere_ind];
            if (col_ind < 3) {
                // sphere sphere_ind, robot batch_ind (FFW_SG2_SINGLE_BATCH_SIZE robots), coord col_ind
                sphere_pos_approx[sphere_ind * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + col_ind] = 
                    T_base[T_memory_idx*16 + col_ind] * ffw_sg2_single_approx_spheres_array[sphere_ind].x +
                    T_base[T_memory_idx*16 + col_ind + M] * ffw_sg2_single_approx_spheres_array[sphere_ind].y +
                    T_base[T_memory_idx*16 + col_ind + M*2] * ffw_sg2_single_approx_spheres_array[sphere_ind].z +
                    T_base[T_memory_idx*16 + col_ind + M*3];
            }
            joint_to_sphere_ind++;
        }
        joint_to_sphere_ind++;
        __syncthreads();
    }
}

// 4 threads per discretized motion for self-collision check
template <>
__device__ bool self_collision_check_approx<ppln::robots::FfwSg2Single>(volatile float* sphere_pos_approx, volatile int* joint_in_collision, const int tid){
    const int thread_ind = tid % 4;
    const int batch_ind = tid / 4;
    bool out = true;
    for (int i = thread_ind; i < FFW_SG2_SINGLE_APPROX_SELF_CC_RANGE_COUNT; i+=4) {
        int sphere_1_ind = ffw_sg2_single_approx_self_cc_ranges[i][0];
        float sphere_1[3] = {
            sphere_pos_approx[sphere_1_ind * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 0],
            sphere_pos_approx[sphere_1_ind * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 1],
            sphere_pos_approx[sphere_1_ind * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 2]
        };
        for (int j = ffw_sg2_single_approx_self_cc_ranges[i][1]; j <= ffw_sg2_single_approx_self_cc_ranges[i][2]; j++) {
            float sphere_2[3] = {
                sphere_pos_approx[j * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 0],
                sphere_pos_approx[j * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 1],
                sphere_pos_approx[j * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 2]
            };
            if (sphere_sphere_self_collision(
                sphere_1[0], sphere_1[1], sphere_1[2], ffw_sg2_single_approx_spheres_array[sphere_1_ind].w,
                sphere_2[0], sphere_2[1], sphere_2[2], ffw_sg2_single_approx_spheres_array[j].w
            )){
                atomicAdd((int*)&joint_in_collision[FFW_SG2_SINGLE_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_single_approx_sphere_to_joint[sphere_1_ind]], 1);
                out = false;
            }
        } 
    }
    return out;
}

// 4 threads per discretized motion for env collision check
template <>
__device__ bool env_collision_check_approx<ppln::robots::FfwSg2Single>(volatile float* sphere_pos_approx, volatile int* joint_in_collision, ppln::collision::Environment<float> *env, const int tid){
    const int thread_ind = tid % 4;
    const int batch_ind = tid / 4;
    bool out = true;

    for (int i = thread_ind; i < FFW_SG2_SINGLE_APPROX_SPHERE_COUNT; i += 4){
        // sphere i, robot batch_ind (32 robots)
        if ( 
            sphere_environment_in_collision(
                env,
                sphere_pos_approx[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 0],
                sphere_pos_approx[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 1],
                sphere_pos_approx[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 2],
                ffw_sg2_single_approx_spheres_array[i].w
            )
        ) {
            atomicAdd((int*)&joint_in_collision[FFW_SG2_SINGLE_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_single_approx_sphere_to_joint[i]],1);
            out = false;
        } 
    }
    return out;
}




#define FFW_SG2_SINGLE_SPHERE_COUNT 124
#define FFW_SG2_SINGLE_JOINT_COUNT 9
#define FFW_SG2_SINGLE_SELF_CC_RANGE_COUNT 116

__device__ __constant__ float4 ffw_sg2_single_spheres_array[124] = {
    { -0.136f, 0.0f, 0.926f, 0.07f },
    { -0.136f, 0.0f, 0.794f, 0.07f },
    { -0.136f, 0.0f, 0.544f, 0.07f },
    { -0.136f, 0.0f, 0.667f, 0.07f },
    { -0.136f, 0.0f, 1.049f, 0.07f },
    { -0.136f, 0.0f, 1.172f, 0.07f },
    { -0.136f, 0.0f, 1.295f, 0.07f },
    { -0.136f, 0.0f, 1.42f, 0.07f },
    { -0.136f, 0.0f, 1.51f, 0.07f },
    { 0.009f, -0.062f, -0.026f, 0.1f },
    { 0.0f, 0.066f, -0.027f, 0.1f },
    { 0.021f, 0.009f, -0.023f, 0.1f },
    { 0.0f, -0.045f, -0.139f, 0.1f },
    { 0.0f, 0.042f, -0.136f, 0.1f },
    { 0.0f, 0.0f, -0.189f, 0.1f },
    { -0.035f, 0.2195f, 0.007f, 0.03518f },
    { -0.032f, 0.2305f, -0.008f, 0.03518f },
    { 0.032f, 0.2375f, -0.002f, 0.03518f },
    { 0.011f, 0.2025f, 0.001f, 0.03443f },
    { -0.017f, 0.2265f, -0.013f, 0.03443f },
    { -0.011f, 0.2115f, -0.02f, 0.03443f },
    { 0.043f, 0.2315f, 0.013f, 0.03443f },
    { -0.002f, 0.2305f, 0.012f, 0.03443f },
    { 0.027f, 0.2075f, 0.011f, 0.03294f },
    { 0.028f, 0.2355f, -0.011f, 0.03219f },
    { -0.007f, 0.2325f, -0.161f, 0.03516f },
    { 0.007f, 0.2295f, -0.093f, 0.03516f },
    { 0.003f, 0.2345f, -0.193f, 0.03457f },
    { 0.009f, 0.2265f, -0.184f, 0.03457f },
    { 0.007f, 0.2295f, -0.155f, 0.03516f },
    { -0.01f, 0.2275f, -0.136f, 0.03516f },
    { -0.005f, 0.2295f, -0.195f, 0.03457f },
    { 0.002f, 0.2315f, -0.18f, 0.03457f },
    { -0.004f, 0.2285f, -0.145f, 0.03339f },
    { -0.011f, 0.2215f, -0.174f, 0.03457f },
    { 0.034f, 0.2085f, -0.292f, 0.03383f },
    { 0.023f, 0.2285f, -0.29f, 0.03383f },
    { 0.032f, 0.2455f, -0.3f, 0.03383f },
    { 0.008f, 0.2315f, -0.265f, 0.03383f },
    { 0.041f, 0.2315f, -0.292f, 0.03383f },
    { 0.045f, 0.2205f, -0.307f, 0.03222f },
    { 0.043f, 0.2415f, -0.302f, 0.03383f },
    { 0.045f, 0.2675f, -0.295f, 0.03142f },
    { 0.04f, 0.2595f, -0.294f, 0.03303f },
    { 0.027f, 0.2005f, -0.298f, 0.03303f },
    { -0.009996f, 0.2185f, -0.39f, 0.03345f },
    { -0.004996f, 0.2305f, -0.44f, 0.03345f },
    { 0.003004f, 0.2245f, -0.462f, 0.03345f },
    { -0.001996f, 0.2205f, -0.442f, 0.03345f },
    { 0.004004f, 0.2525f, -0.383f, 0.03345f },
    { 0.005004f, 0.2275f, -0.462f, 0.03345f },
    { 0.002004f, 0.2275f, -0.467f, 0.03232f },
    { -0.000996f, 0.2215f, -0.467f, 0.03232f },
    { 0.001004f, 0.2225f, -0.438f, 0.03345f },
    { -0.000996f, 0.2285f, -0.429f, 0.03119f },
    { 0.004f, 0.2075f, -0.5509f, 0.03351f },
    { -0.011f, 0.2475f, -0.5609f, 0.03351f },
    { 0.003f, 0.2575f, -0.5489f, 0.03351f },
    { -0.003f, 0.2645f, -0.5469f, 0.03351f },
    { -0.013f, 0.2395f, -0.5559f, 0.03351f },
    { 0.003f, 0.2545f, -0.5549f, 0.03285f },
    { 0.006f, 0.2085f, -0.5429f, 0.03351f },
    { 0.006f, 0.2435f, -0.5569f, 0.03285f },
    { 0.0f, 0.2295f, -0.5309f, 0.03219f },
    { -0.01f, 0.2295f, -0.5399f, 0.03351f },
    { 0.036f, 0.2275f, -0.643f, 0.02f },
    { 0.005f, 0.2275f, -0.642f, 0.02f },
    { -0.021f, 0.2275f, -0.643f, 0.02f },
    { 0.0f, 0.2275f, -0.621f, 0.02f },
    { 0.0f, 0.2745f, -0.601f, 0.02f },
    { 0.044f, 0.2275f, -0.6845f, 0.02f },
    { 0.026f, 0.2275f, -0.7055f, 0.02f },
    { -0.004f, 0.2275f, -0.7055f, 0.02f },
    { -0.026f, 0.2275f, -0.6955f, 0.02f },
    { 0.068f, 0.2275f, -0.6955f, 0.02f },
    { 0.101f, 0.2275f, -0.7055f, 0.02f },
    { 0.119f, 0.2275f, -0.7065f, 0.02f },
    { 0.0f, 0.2075f, -0.7535f, 0.02f },
    { 0.0f, 0.2495f, -0.7545f, 0.02f },
    { 0.0f, 0.1825f, -0.7745f, 0.02f },
    { 0.0f, 0.167137f, -0.829f, 0.02f },
    { 0.0f, 0.2715f, -0.7715f, 0.02f },
    { 0.0f, 0.288863f, -0.828f, 0.02f },
    { 0.0f, -0.068f, -0.002f, 0.04f },
    { -0.022f, -0.12f, -0.002f, 0.04f },
    { 0.036f, -0.133f, 0.0f, 0.04f },
    { 0.0f, 0.0f, -0.091f, 0.04f },
    { 0.001f, 0.0f, -0.152f, 0.04f },
    { 0.0f, 0.0f, -0.192f, 0.04f },
    { 0.007f, 0.0f, -0.098f, 0.04f },
    { 0.042f, -0.027f, -0.134f, 0.04f },
    { 0.044f, 0.018f, -0.134f, 0.04f },
    { -0.041f, 0.0f, -0.095f, 0.04f },
    { -0.041f, 0.0f, -0.167f, 0.04f },
    { -0.041f, 0.0f, -0.131f, 0.04f },
    { -0.04f, -0.05f, -0.064f, 0.02f },
    { 0.0f, 0.015f, -0.102f, 0.04f },
    { 0.0f, -0.039f, -0.103f, 0.04f },
    { 0.0f, -0.051f, -0.049f, 0.02f },
    { -0.022f, 0.0f, -0.09f, 0.02f },
    { -0.011f, 0.0f, -0.09f, 0.02f },
    { 0.014f, 0.0f, -0.092f, 0.02f },
    { 0.038f, 0.0f, -0.088f, 0.02f },
    { -0.034f, 0.0f, -0.05f, 0.02f },
    { -0.013f, 0.0f, -0.064f, 0.02f },
    { 0.021f, 0.0f, -0.066f, 0.02f },
    { 0.047f, 0.0f, -0.054f, 0.02f },
    { 0.078f, 0.0f, -0.057f, 0.02f },
    { 0.105f, 0.0f, -0.062f, 0.02f },
    { 0.119f, 0.0f, -0.065f, 0.02f },
    { 0.0f, 0.023f, -0.116f, 0.02f },
    { 0.0f, -0.019f, -0.114f, 0.02f },
    { 0.0f, -0.041f, -0.126f, 0.02f },
    { 0.0f, -0.064363f, -0.1835f, 0.02f },
    { 0.0f, 0.042f, -0.127f, 0.02f },
    { 0.0f, 0.054363f, -0.1855f, 0.02f },
    { 0.124057f, -0.058f, 0.138503f, 0.04f },
    { 0.112057f, 0.069f, 0.134503f, 0.04f },
    { 0.130057f, 0.0f, 0.138503f, 0.04f },
    { 0.086057f, -0.051f, 0.140503f, 0.04f },
    { 0.086057f, 0.055f, 0.145503f, 0.04f },
    { 0.010057f, 0.0f, 0.143503f, 0.04f },
    { 0.041057f, -0.048f, 0.143503f, 0.04f },
    { 0.037057f, 0.045f, 0.144503f, 0.04f }
};

__device__ __constant__ float ffw_sg2_single_fixed_transforms[] = {
    // joint 0
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 1
    1.0, 0.0, 0.0, -0.0199,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 1.4316,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 2
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, -0.1045,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 3
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, -0.123,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 4
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.165,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 5
    1.0, 0.0, 0.0, 0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.135,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 6
    1.0, 0.0, 0.0, -0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1489,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 7
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1041,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 8
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.0885,
    0.0, 0.0, 0.0, 1.0,
    
    
};

__device__ __constant__ int ffw_sg2_single_sphere_to_joint[124] = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    2,
    3,
    3,
    3,
    4,
    4,
    4,
    5,
    5,
    5,
    5,
    6,
    6,
    7,
    7,
    7,
    7,
    7,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
};

__device__ __constant__ int ffw_sg2_single_flattened_joint_to_spheres[133] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    -1,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    116,
    117,
    118,
    119,
    120,
    121,
    122,
    123,
    -1,
    83,
    84,
    85,
    -1,
    86,
    87,
    88,
    -1,
    89,
    90,
    91,
    -1,
    92,
    93,
    94,
    95,
    -1,
    96,
    97,
    -1,
    98,
    99,
    100,
    101,
    102,
    -1,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    -1
};

__device__ __constant__ int ffw_sg2_single_joint_types[] = {
    3,
    2,
    4,
    3,
    5,
    4,
    5,
    4,
    3
};

__device__ __constant__ int ffw_sg2_single_self_cc_ranges[116][3] = {
    { 0, 15, 123 },
    { 1, 15, 123 },
    { 2, 15, 123 },
    { 3, 15, 123 },
    { 4, 15, 123 },
    { 5, 15, 123 },
    { 6, 15, 123 },
    { 7, 15, 123 },
    { 8, 15, 123 },
    { 9, 86, 115 },
    { 10, 86, 115 },
    { 11, 86, 115 },
    { 12, 86, 115 },
    { 13, 86, 115 },
    { 14, 86, 115 },
    { 15, 83, 115 },
    { 16, 83, 115 },
    { 17, 83, 115 },
    { 18, 83, 115 },
    { 19, 83, 115 },
    { 20, 83, 115 },
    { 21, 83, 115 },
    { 22, 83, 115 },
    { 23, 83, 115 },
    { 24, 83, 115 },
    { 25, 83, 115 },
    { 26, 83, 115 },
    { 27, 83, 115 },
    { 28, 83, 115 },
    { 29, 83, 115 },
    { 30, 83, 115 },
    { 31, 83, 115 },
    { 32, 83, 115 },
    { 33, 83, 115 },
    { 34, 83, 115 },
    { 35, 83, 115 },
    { 36, 83, 115 },
    { 37, 83, 115 },
    { 38, 83, 115 },
    { 39, 83, 115 },
    { 40, 83, 115 },
    { 41, 83, 115 },
    { 42, 83, 115 },
    { 43, 83, 115 },
    { 44, 83, 115 },
    { 45, 83, 115 },
    { 46, 83, 115 },
    { 47, 83, 115 },
    { 48, 83, 115 },
    { 49, 83, 115 },
    { 50, 83, 115 },
    { 51, 83, 115 },
    { 52, 83, 115 },
    { 53, 83, 115 },
    { 54, 83, 115 },
    { 55, 83, 115 },
    { 56, 83, 115 },
    { 57, 83, 115 },
    { 58, 83, 115 },
    { 59, 83, 115 },
    { 60, 83, 115 },
    { 61, 83, 115 },
    { 62, 83, 115 },
    { 63, 83, 115 },
    { 64, 83, 115 },
    { 65, 83, 115 },
    { 66, 83, 115 },
    { 67, 83, 115 },
    { 68, 83, 115 },
    { 69, 83, 115 },
    { 70, 83, 115 },
    { 71, 83, 115 },
    { 72, 83, 115 },
    { 73, 83, 115 },
    { 74, 83, 115 },
    { 75, 83, 115 },
    { 76, 83, 115 },
    { 77, 83, 115 },
    { 78, 83, 115 },
    { 79, 83, 115 },
    { 80, 83, 115 },
    { 81, 83, 115 },
    { 82, 83, 115 },
    { 83, 89, 123 },
    { 84, 89, 123 },
    { 85, 89, 123 },
    { 86, 92, 123 },
    { 87, 92, 123 },
    { 88, 92, 123 },
    { 89, 96, 123 },
    { 90, 96, 123 },
    { 91, 96, 123 },
    { 92, 98, 123 },
    { 93, 98, 123 },
    { 94, 98, 123 },
    { 95, 98, 123 },
    { 96, 103, 123 },
    { 97, 103, 123 },
    { 98, 110, 123 },
    { 99, 110, 123 },
    { 100, 110, 123 },
    { 101, 110, 123 },
    { 102, 110, 123 },
    { 103, 116, 123 },
    { 104, 116, 123 },
    { 105, 116, 123 },
    { 106, 116, 123 },
    { 107, 116, 123 },
    { 108, 116, 123 },
    { 109, 116, 123 },
    { 110, 116, 123 },
    { 111, 116, 123 },
    { 112, 116, 123 },
    { 113, 116, 123 },
    { 114, 116, 123 },
    { 115, 116, 123 }
};

__device__ __constant__ int ffw_sg2_single_joint_parents[9] = {
    0,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7
};

__device__ __constant__ int ffw_sg2_single_T_memory_idx[9] = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
};

__device__ __constant__ int ffw_sg2_single_dfs_order[9] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8
};

__device__ __constant__ int ffw_sg2_single_joint_id_to_dof[9] = {
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7
};

template <>
__device__ void fk<ppln::robots::FfwSg2Single>(
    const float* q,
    volatile float* sphere_pos, // 124 spheres x 16 robots x 3 coordinates (each column is a robot)
    float *T, // 16 robots x 1 x 4x4 transform matrix , column major
    const int tid
)
{
    // every 4 threads are responsible for one column of the transform matrix T
    // make_transform will calculate the necessary column of T_step needed for the thread
    const int col_ind = tid % 4;
    const int batch_ind = tid / 4;

    int T_offset = batch_ind * 1 * 16;
    float T_step_col[4]; // 4x1 column of the joint transform matrix for this thread
    float *T_base = T + T_offset; // 4x4 transform matrix for the batch
    
    #pragma unroll
    for (int i = 0; i < 1; ++i) {
        float *T_col_i = T_base + i * 16 + col_ind * 4;
        for (int r=0; r<4; r++) {
            T_col_i[r] = 0.0f;
        }
        T_col_i[col_ind] = 1.0f;
    }
    __syncthreads();

    int joint_to_sphere_ind = 0;

    for (int j = 0; j < FFW_SG2_SINGLE_JOINT_COUNT; ++j) {
        int i = ffw_sg2_single_dfs_order[j];
        float T_col_tmp[4];
        int parent_idx = ffw_sg2_single_joint_parents[i];
        int T_memory_idx_parent = ffw_sg2_single_T_memory_idx[parent_idx];
        int T_memory_idx = ffw_sg2_single_T_memory_idx[i];
        int q_idx = ffw_sg2_single_joint_id_to_dof[i];
        if (j > 0) {
            int ft_addr_start = i * 16;
            int joint_type = ffw_sg2_single_joint_types[i];

            if (joint_type <= FFW_SG2_SINGLE_Z_PRISM) {
                prism_fn(&ffw_sg2_single_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col, joint_type);
            }
            else if (joint_type == FFW_SG2_SINGLE_X_ROT) {
                xrot_fn(&ffw_sg2_single_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            else if (joint_type == FFW_SG2_SINGLE_Y_ROT) {
                yrot_fn(&ffw_sg2_single_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            else if (joint_type == FFW_SG2_SINGLE_Z_ROT) {
                zrot_fn(&ffw_sg2_single_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            
            for (int r=0; r<4; r++){
                T_col_tmp[r] = dot4_col(&T_base[T_memory_idx_parent*16 + r], T_step_col);
            }
            for (int r=0; r<4; r++){
                T_base[T_memory_idx*16 + col_ind*4 + r] = T_col_tmp[r];
            }
        }
        __syncwarp();
        while (ffw_sg2_single_flattened_joint_to_spheres[joint_to_sphere_ind] != -1) {
            int sphere_ind = ffw_sg2_single_flattened_joint_to_spheres[joint_to_sphere_ind];
            if (col_ind < 3) {
                // sphere sphere_ind, robot batch_ind (FFW_SG2_SINGLE_BATCH_SIZE robots), coord col_ind
                sphere_pos[sphere_ind * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + col_ind] = 
                    T_base[T_memory_idx*16 + col_ind] * ffw_sg2_single_spheres_array[sphere_ind].x +
                    T_base[T_memory_idx*16 + col_ind + M] * ffw_sg2_single_spheres_array[sphere_ind].y +
                    T_base[T_memory_idx*16 + col_ind + M*2] * ffw_sg2_single_spheres_array[sphere_ind].z +
                    T_base[T_memory_idx*16 + col_ind + M*3];
            }
            joint_to_sphere_ind++;
        }
        joint_to_sphere_ind++;
        __syncthreads();
    }
}

// 4 threads per discretized motion for self-collision check
template <>
__device__ bool self_collision_check<ppln::robots::FfwSg2Single>(volatile float* sphere_pos, volatile int* joint_in_collision, const int tid){
    const int thread_ind = tid % 4;
    const int batch_ind = tid / 4;
    bool has_collision = false;

    for (int i = thread_ind; i < FFW_SG2_SINGLE_SELF_CC_RANGE_COUNT; i += 4) {
        if (warp_any_active_mask(has_collision)) return false;
        int sphere_1_ind = ffw_sg2_single_self_cc_ranges[i][0];
        if (joint_in_collision[FFW_SG2_SINGLE_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_single_sphere_to_joint[sphere_1_ind]] == 0) continue;
        float sphere_1[3] = {
            sphere_pos[sphere_1_ind * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 0],
            sphere_pos[sphere_1_ind * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 1],
            sphere_pos[sphere_1_ind * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 2]
        };
        for (int j = ffw_sg2_single_self_cc_ranges[i][1]; j <= ffw_sg2_single_self_cc_ranges[i][2]; j++) {
            float sphere_2[3] = {
                sphere_pos[j * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 0],
                sphere_pos[j * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 1],
                sphere_pos[j * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 2]
            };
            if (sphere_sphere_self_collision(
                sphere_1[0], sphere_1[1], sphere_1[2], ffw_sg2_single_spheres_array[sphere_1_ind].w,
                sphere_2[0], sphere_2[1], sphere_2[2], ffw_sg2_single_spheres_array[j].w
            )){
                //return false;
                has_collision=true;
            }
        }
    }
    return !has_collision;

}

// 4 threads per discretized motion for env collision check
template <>
__device__ bool env_collision_check<ppln::robots::FfwSg2Single>(volatile float* sphere_pos, volatile int* joint_in_collision, ppln::collision::Environment<float> *env, const int tid){
    const int thread_ind = tid % 4;
    const int batch_ind = tid / 4;
    bool has_collision=false;

    for (int i = thread_ind; i < FFW_SG2_SINGLE_SPHERE_COUNT-FFW_SG2_SINGLE_SPHERE_COUNT%4; i += 4){
        // sphere i, robot batch_ind (16 robots)
        if (joint_in_collision[FFW_SG2_SINGLE_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_single_sphere_to_joint[i]] > 0 && 
            sphere_environment_in_collision(
                env,
                sphere_pos[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 0],
                sphere_pos[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 1],
                sphere_pos[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 2],
                ffw_sg2_single_spheres_array[i].w
            )
        ) {
            //return false;
            has_collision=true;
        } 
        if (warp_any_full_mask(has_collision)) return false;
    }
    int i=FFW_SG2_SINGLE_SPHERE_COUNT-1-thread_ind;
    if (joint_in_collision[FFW_SG2_SINGLE_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_single_sphere_to_joint[i]] > 0 && 
        sphere_environment_in_collision(
            env,
            sphere_pos[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 0],
            sphere_pos[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 1],
            sphere_pos[i * FFW_SG2_SINGLE_BATCH_SIZE * 3 + batch_ind * 3 + 2],
            ffw_sg2_single_spheres_array[i].w
        )
    ) {
        return false;
    } 
    return true;
}
}
