#pragma once

// Generated by CoMMALab/cricket gpu-cc-early-exit at commit
// 98582c35d81c6ed0d8c4badb7fdf78327523524c, then validated and namespaced by
// resources/ffw_sg2/postprocess_cricket_header.py.

namespace ppln::collision {





#define FFW_SG2_APPROX_SPHERE_COUNT 27
#define FFW_SG2_APPROX_JOINT_COUNT 16
#define FFW_SG2_APPROX_SELF_CC_RANGE_COUNT 27
#define FFW_SG2_FIXED -1
#define FFW_SG2_X_PRISM 0
#define FFW_SG2_Y_PRISM 1
#define FFW_SG2_Z_PRISM 2
#define FFW_SG2_X_ROT 3
#define FFW_SG2_Y_ROT 4
#define FFW_SG2_Z_ROT 5
#define FFW_SG2_BATCH_SIZE 16
#define FFW_SG2_JOINT_FLAG_STRIDE 16
#define FFW_SG2_TRANSFORM_SLOTS 2

__device__ __constant__ float4 ffw_sg2_approx_spheres_array[27] = {
    { -0.136f, 0.0f, 1.027f, 0.553001f },
    { 0.0105f, 0.002f, -0.106f, 0.202462f },
    { 0.003625f, 0.115875f, -0.0035f, 0.078549f },
    { -0.001f, 0.0005f, -0.143705f, 0.086515f },
    { 0.025695f, 0.005695f, -0.120195f, 0.071988f },
    { -0.0435f, 0.008f, -0.124435f, 0.078707f },
    { -0.0035f, 0.0085f, -0.09766f, 0.063299f },
    { 0.0075f, 0.0235f, -0.069f, 0.062492f },
    { 0.0465f, 0.0f, -0.054f, 0.093331f },
    { 0.0f, 0.001f, -0.1125f, 0.041007f },
    { 0.0f, -0.045f, -0.133f, 0.020001f },
    { 0.0f, -0.060363f, -0.1875f, 0.020001f },
    { 0.0f, 0.044f, -0.13f, 0.020001f },
    { 0.0f, 0.061363f, -0.1865f, 0.020001f },
    { 0.007f, -0.1005f, -0.001f, 0.08357f },
    { 0.0005f, 0.0f, -0.1415f, 0.090503f },
    { 0.0255f, -0.0045f, -0.116f, 0.074243f },
    { -0.041f, -0.015f, -0.1255f, 0.09077f },
    { 0.0f, -0.012f, -0.1025f, 0.067006f },
    { 0.008f, -0.0255f, -0.0705f, 0.063938f },
    { 0.0425f, 0.0f, -0.058f, 0.096918f },
    { 0.0f, 0.002f, -0.115f, 0.041025f },
    { 0.0f, -0.041f, -0.126f, 0.020001f },
    { 0.0f, -0.064363f, -0.1835f, 0.020001f },
    { 0.0f, 0.042f, -0.127f, 0.020001f },
    { 0.0f, 0.054363f, -0.1855f, 0.020001f },
    { 0.070057f, 0.0055f, 0.140003f, 0.123371f }
};

__device__ __constant__ float ffw_sg2_approx_fixed_transforms[] = {
    // joint 0
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 1
    1.0, 0.0, 0.0, -0.0199,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 1.4316,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 2
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.1045,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 3
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.123,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 4
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.165,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 5
    1.0, 0.0, 0.0, 0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.135,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 6
    1.0, 0.0, 0.0, -0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1489,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 7
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1041,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 8
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.0885,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 9
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, -0.1045,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 10
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, -0.123,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 11
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.165,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 12
    1.0, 0.0, 0.0, 0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.135,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 13
    1.0, 0.0, 0.0, -0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1489,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 14
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1041,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 15
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.0885,
    0.0, 0.0, 0.0, 1.0,
    
    
};

__device__ __constant__ int ffw_sg2_approx_sphere_to_joint[27] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    8,
    8,
    8,
    8,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    15,
    15,
    15,
    15,
    15,
    1
};

__device__ __constant__ int ffw_sg2_approx_flattened_joint_to_spheres[43] = {
    0,
    -1,
    1,
    26,
    -1,
    2,
    -1,
    3,
    -1,
    4,
    -1,
    5,
    -1,
    6,
    -1,
    7,
    -1,
    8,
    9,
    10,
    11,
    12,
    13,
    -1,
    14,
    -1,
    15,
    -1,
    16,
    -1,
    17,
    -1,
    18,
    -1,
    19,
    -1,
    20,
    21,
    22,
    23,
    24,
    25,
    -1
};

__device__ __constant__ int ffw_sg2_approx_joint_types[] = {
    3,
    2,
    4,
    3,
    5,
    4,
    5,
    4,
    3,
    4,
    3,
    5,
    4,
    5,
    4,
    3
};

__device__ __constant__ int ffw_sg2_approx_self_cc_ranges[27][3] = {
    { 0, 2, 26 },
    { 1, 3, 13 },
    { 1, 15, 25 },
    { 2, 4, 26 },
    { 3, 5, 26 },
    { 4, 6, 26 },
    { 5, 7, 26 },
    { 6, 8, 26 },
    { 7, 9, 26 },
    { 8, 14, 26 },
    { 9, 14, 26 },
    { 10, 14, 26 },
    { 11, 14, 26 },
    { 12, 14, 26 },
    { 13, 14, 26 },
    { 14, 16, 26 },
    { 15, 17, 26 },
    { 16, 18, 26 },
    { 17, 19, 26 },
    { 18, 20, 26 },
    { 19, 21, 26 },
    { 20, 26, 26 },
    { 21, 26, 26 },
    { 22, 26, 26 },
    { 23, 26, 26 },
    { 24, 26, 26 },
    { 25, 26, 26 }
};

__device__ __constant__ int ffw_sg2_approx_joint_parents[16] = {
    0,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    1,
    9,
    10,
    11,
    12,
    13,
    14
};

__device__ __constant__ int ffw_sg2_approx_T_memory_idx[16] = {
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
};

__device__ __constant__ int ffw_sg2_approx_dfs_order[16] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
};

__device__ __constant__ int ffw_sg2_approx_joint_id_to_dof[16] = {
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
};

template <>
__device__ void fk_approx<ppln::robots::FfwSg2>(
    const float* q,
    volatile float* sphere_pos_approx, // 27 spheres x 16 robots x 3 coordinates (each column is a robot)
    float *T, // 16 robots x 2 x 4x4 transform matrix , column major
    const int tid
)
{
    // every 4 threads are responsible for one column of the transform matrix T
    // make_transform will calculate the necessary column of T_step needed for the thread
    const int col_ind = tid % 4;
    const int batch_ind = tid / 4;

    int T_offset = batch_ind * 2 * 16;
    float T_step_col[4]; // 4x1 column of the joint transform matrix for this thread
    float *T_base = T + T_offset; // 4x4 transform matrix for the batch
    
    #pragma unroll
    for (int i = 0; i < 2; ++i) {
        float *T_col_i = T_base + i * 16 + col_ind * 4;
        for (int r=0; r<4; r++) {
            T_col_i[r] = 0.0f;
        }
        T_col_i[col_ind] = 1.0f;
    }
    __syncthreads();

    int joint_to_sphere_ind = 0;

    for (int j = 0; j < FFW_SG2_APPROX_JOINT_COUNT; ++j) {
        int i = ffw_sg2_approx_dfs_order[j];
        float T_col_tmp[4];
        int parent_idx = ffw_sg2_approx_joint_parents[i];
        int T_memory_idx_parent = ffw_sg2_approx_T_memory_idx[parent_idx];
        int T_memory_idx = ffw_sg2_approx_T_memory_idx[i];
        int q_idx = ffw_sg2_approx_joint_id_to_dof[i];
        if (j > 0) {
            int ft_addr_start = i * 16;
            int joint_type = ffw_sg2_approx_joint_types[i];

            if (joint_type <= FFW_SG2_Z_PRISM) {
                prism_fn(&ffw_sg2_approx_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col, joint_type);
            }
            else if (joint_type == FFW_SG2_X_ROT) {
                xrot_fn(&ffw_sg2_approx_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            else if (joint_type == FFW_SG2_Y_ROT) {
                yrot_fn(&ffw_sg2_approx_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            else if (joint_type == FFW_SG2_Z_ROT) {
                zrot_fn(&ffw_sg2_approx_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            
            for (int r=0; r<4; r++){
                T_col_tmp[r] = dot4_col(&T_base[T_memory_idx_parent*16 + r], T_step_col);
            }
            for (int r=0; r<4; r++){
                T_base[T_memory_idx*16 + col_ind*4 + r] = T_col_tmp[r];
            }
        }
        __syncwarp();
        while (ffw_sg2_approx_flattened_joint_to_spheres[joint_to_sphere_ind] != -1) {
            int sphere_ind = ffw_sg2_approx_flattened_joint_to_spheres[joint_to_sphere_ind];
            if (col_ind < 3) {
                // sphere sphere_ind, robot batch_ind (FFW_SG2_BATCH_SIZE robots), coord col_ind
                sphere_pos_approx[sphere_ind * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + col_ind] = 
                    T_base[T_memory_idx*16 + col_ind] * ffw_sg2_approx_spheres_array[sphere_ind].x +
                    T_base[T_memory_idx*16 + col_ind + M] * ffw_sg2_approx_spheres_array[sphere_ind].y +
                    T_base[T_memory_idx*16 + col_ind + M*2] * ffw_sg2_approx_spheres_array[sphere_ind].z +
                    T_base[T_memory_idx*16 + col_ind + M*3];
            }
            joint_to_sphere_ind++;
        }
        joint_to_sphere_ind++;
        __syncthreads();
    }
}

// 4 threads per discretized motion for self-collision check
template <>
__device__ bool self_collision_check_approx<ppln::robots::FfwSg2>(volatile float* sphere_pos_approx, volatile int* joint_in_collision, const int tid){
    const int thread_ind = tid % 4;
    const int batch_ind = tid / 4;
    bool out = true;
    for (int i = thread_ind; i < FFW_SG2_APPROX_SELF_CC_RANGE_COUNT; i+=4) {
        int sphere_1_ind = ffw_sg2_approx_self_cc_ranges[i][0];
        float sphere_1[3] = {
            sphere_pos_approx[sphere_1_ind * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 0],
            sphere_pos_approx[sphere_1_ind * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 1],
            sphere_pos_approx[sphere_1_ind * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 2]
        };
        for (int j = ffw_sg2_approx_self_cc_ranges[i][1]; j <= ffw_sg2_approx_self_cc_ranges[i][2]; j++) {
            float sphere_2[3] = {
                sphere_pos_approx[j * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 0],
                sphere_pos_approx[j * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 1],
                sphere_pos_approx[j * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 2]
            };
            if (sphere_sphere_self_collision(
                sphere_1[0], sphere_1[1], sphere_1[2], ffw_sg2_approx_spheres_array[sphere_1_ind].w,
                sphere_2[0], sphere_2[1], sphere_2[2], ffw_sg2_approx_spheres_array[j].w
            )){
                atomicAdd((int*)&joint_in_collision[FFW_SG2_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_approx_sphere_to_joint[sphere_1_ind]], 1);
                out = false;
            }
        } 
    }
    return out;
}

// 4 threads per discretized motion for env collision check
template <>
__device__ bool env_collision_check_approx<ppln::robots::FfwSg2>(volatile float* sphere_pos_approx, volatile int* joint_in_collision, ppln::collision::Environment<float> *env, const int tid){
    const int thread_ind = tid % 4;
    const int batch_ind = tid / 4;
    bool out = true;

    for (int i = thread_ind; i < FFW_SG2_APPROX_SPHERE_COUNT; i += 4){
        // sphere i, robot batch_ind (32 robots)
        if ( 
            sphere_environment_in_collision(
                env,
                sphere_pos_approx[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 0],
                sphere_pos_approx[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 1],
                sphere_pos_approx[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 2],
                ffw_sg2_approx_spheres_array[i].w
            )
        ) {
            atomicAdd((int*)&joint_in_collision[FFW_SG2_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_approx_sphere_to_joint[i]],1);
            out = false;
        } 
    }
    return out;
}




#define FFW_SG2_SPHERE_COUNT 124
#define FFW_SG2_JOINT_COUNT 16
#define FFW_SG2_SELF_CC_RANGE_COUNT 122

__device__ __constant__ float4 ffw_sg2_spheres_array[124] = {
    { -0.136f, 0.0f, 0.926f, 0.07f },
    { -0.136f, 0.0f, 0.794f, 0.07f },
    { -0.136f, 0.0f, 0.544f, 0.07f },
    { -0.136f, 0.0f, 0.667f, 0.07f },
    { -0.136f, 0.0f, 1.049f, 0.07f },
    { -0.136f, 0.0f, 1.172f, 0.07f },
    { -0.136f, 0.0f, 1.295f, 0.07f },
    { -0.136f, 0.0f, 1.42f, 0.07f },
    { -0.136f, 0.0f, 1.51f, 0.07f },
    { 0.009f, -0.062f, -0.026f, 0.1f },
    { 0.0f, 0.066f, -0.027f, 0.1f },
    { 0.021f, 0.009f, -0.023f, 0.1f },
    { 0.0f, -0.045f, -0.139f, 0.1f },
    { 0.0f, 0.042f, -0.136f, 0.1f },
    { 0.0f, 0.0f, -0.189f, 0.1f },
    { -0.035f, 0.115f, 0.007f, 0.03518f },
    { -0.032f, 0.126f, -0.008f, 0.03518f },
    { 0.032f, 0.133f, -0.002f, 0.03518f },
    { 0.011f, 0.098f, 0.001f, 0.03443f },
    { -0.017f, 0.122f, -0.013f, 0.03443f },
    { -0.011f, 0.107f, -0.02f, 0.03443f },
    { 0.043f, 0.127f, 0.013f, 0.03443f },
    { -0.002f, 0.126f, 0.012f, 0.03443f },
    { 0.027f, 0.103f, 0.011f, 0.03294f },
    { 0.028f, 0.131f, -0.011f, 0.03219f },
    { -0.007f, 0.005f, -0.161f, 0.03516f },
    { 0.007f, 0.002f, -0.093f, 0.03516f },
    { 0.003f, 0.007f, -0.193f, 0.03457f },
    { 0.009f, -0.001f, -0.184f, 0.03457f },
    { 0.007f, 0.002f, -0.155f, 0.03516f },
    { -0.01f, 0.0f, -0.136f, 0.03516f },
    { -0.005f, 0.002f, -0.195f, 0.03457f },
    { 0.002f, 0.004f, -0.18f, 0.03457f },
    { -0.004f, 0.001f, -0.145f, 0.03339f },
    { -0.011f, -0.006f, -0.174f, 0.03457f },
    { 0.034f, -0.019f, -0.127f, 0.03383f },
    { 0.023f, 0.001f, -0.125f, 0.03383f },
    { 0.032f, 0.018f, -0.135f, 0.03383f },
    { 0.008f, 0.004f, -0.1f, 0.03383f },
    { 0.041f, 0.004f, -0.127f, 0.03383f },
    { 0.045f, -0.007f, -0.142f, 0.03222f },
    { 0.043f, 0.014f, -0.137f, 0.03383f },
    { 0.045f, 0.04f, -0.13f, 0.03142f },
    { 0.04f, 0.032f, -0.129f, 0.03303f },
    { 0.027f, -0.027f, -0.133f, 0.03303f },
    { -0.051f, -0.009f, -0.09f, 0.03345f },
    { -0.046f, 0.003f, -0.14f, 0.03345f },
    { -0.038f, -0.003f, -0.162f, 0.03345f },
    { -0.043f, -0.007f, -0.142f, 0.03345f },
    { -0.037f, 0.025f, -0.083f, 0.03345f },
    { -0.036f, 0.0f, -0.162f, 0.03345f },
    { -0.039f, 0.0f, -0.167f, 0.03232f },
    { -0.042f, -0.006f, -0.167f, 0.03232f },
    { -0.04f, -0.005f, -0.138f, 0.03345f },
    { -0.042f, 0.001f, -0.129f, 0.03119f },
    { 0.004f, -0.02f, -0.102f, 0.03351f },
    { -0.011f, 0.02f, -0.112f, 0.03351f },
    { 0.003f, 0.03f, -0.1f, 0.03351f },
    { -0.003f, 0.037f, -0.098f, 0.03351f },
    { -0.013f, 0.012f, -0.107f, 0.03351f },
    { 0.003f, 0.027f, -0.106f, 0.03285f },
    { 0.006f, -0.019f, -0.094f, 0.03351f },
    { 0.006f, 0.016f, -0.108f, 0.03285f },
    { 0.0f, 0.002f, -0.082f, 0.03219f },
    { -0.01f, 0.002f, -0.091f, 0.03351f },
    { 0.036f, 0.0f, -0.09f, 0.02f },
    { 0.005f, 0.0f, -0.089f, 0.02f },
    { -0.021f, 0.0f, -0.09f, 0.02f },
    { 0.0f, 0.0f, -0.068f, 0.02f },
    { 0.0f, 0.047f, -0.048f, 0.02f },
    { 0.044f, 0.0f, -0.043f, 0.02f },
    { 0.026f, 0.0f, -0.064f, 0.02f },
    { -0.004f, 0.0f, -0.064f, 0.02f },
    { -0.026f, 0.0f, -0.054f, 0.02f },
    { 0.068f, 0.0f, -0.054f, 0.02f },
    { 0.101f, 0.0f, -0.064f, 0.02f },
    { 0.119f, 0.0f, -0.065f, 0.02f },
    { 0.0f, -0.02f, -0.112f, 0.02f },
    { 0.0f, 0.022f, -0.113f, 0.02f },
    { 0.0f, -0.045f, -0.133f, 0.02f },
    { 0.0f, -0.060363f, -0.1875f, 0.02f },
    { 0.0f, 0.044f, -0.13f, 0.02f },
    { 0.0f, 0.061363f, -0.1865f, 0.02f },
    { 0.0f, -0.068f, -0.002f, 0.04f },
    { -0.022f, -0.12f, -0.002f, 0.04f },
    { 0.036f, -0.133f, 0.0f, 0.04f },
    { 0.0f, 0.0f, -0.091f, 0.04f },
    { 0.001f, 0.0f, -0.152f, 0.04f },
    { 0.0f, 0.0f, -0.192f, 0.04f },
    { 0.007f, 0.0f, -0.098f, 0.04f },
    { 0.042f, -0.027f, -0.134f, 0.04f },
    { 0.044f, 0.018f, -0.134f, 0.04f },
    { -0.041f, 0.0f, -0.095f, 0.04f },
    { -0.041f, 0.0f, -0.167f, 0.04f },
    { -0.041f, 0.0f, -0.131f, 0.04f },
    { -0.04f, -0.05f, -0.064f, 0.02f },
    { 0.0f, 0.015f, -0.102f, 0.04f },
    { 0.0f, -0.039f, -0.103f, 0.04f },
    { 0.0f, -0.051f, -0.049f, 0.02f },
    { -0.022f, 0.0f, -0.09f, 0.02f },
    { -0.011f, 0.0f, -0.09f, 0.02f },
    { 0.014f, 0.0f, -0.092f, 0.02f },
    { 0.038f, 0.0f, -0.088f, 0.02f },
    { -0.034f, 0.0f, -0.05f, 0.02f },
    { -0.013f, 0.0f, -0.064f, 0.02f },
    { 0.021f, 0.0f, -0.066f, 0.02f },
    { 0.047f, 0.0f, -0.054f, 0.02f },
    { 0.078f, 0.0f, -0.057f, 0.02f },
    { 0.105f, 0.0f, -0.062f, 0.02f },
    { 0.119f, 0.0f, -0.065f, 0.02f },
    { 0.0f, 0.023f, -0.116f, 0.02f },
    { 0.0f, -0.019f, -0.114f, 0.02f },
    { 0.0f, -0.041f, -0.126f, 0.02f },
    { 0.0f, -0.064363f, -0.1835f, 0.02f },
    { 0.0f, 0.042f, -0.127f, 0.02f },
    { 0.0f, 0.054363f, -0.1855f, 0.02f },
    { 0.124057f, -0.058f, 0.138503f, 0.04f },
    { 0.112057f, 0.069f, 0.134503f, 0.04f },
    { 0.130057f, 0.0f, 0.138503f, 0.04f },
    { 0.086057f, -0.051f, 0.140503f, 0.04f },
    { 0.086057f, 0.055f, 0.145503f, 0.04f },
    { 0.010057f, 0.0f, 0.143503f, 0.04f },
    { 0.041057f, -0.048f, 0.143503f, 0.04f },
    { 0.037057f, 0.045f, 0.144503f, 0.04f }
};

__device__ __constant__ float ffw_sg2_fixed_transforms[] = {
    // joint 0
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 1
    1.0, 0.0, 0.0, -0.0199,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 1.4316,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 2
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.1045,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 3
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.123,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 4
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.165,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 5
    1.0, 0.0, 0.0, 0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.135,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 6
    1.0, 0.0, 0.0, -0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1489,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 7
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1041,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 8
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.0885,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 9
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, -0.1045,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 10
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, -0.123,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 11
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.165,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 12
    1.0, 0.0, 0.0, 0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.135,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 13
    1.0, 0.0, 0.0, -0.041004,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1489,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 14
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.1041,
    0.0, 0.0, 0.0, 1.0,
    
    // joint 15
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, -0.0885,
    0.0, 0.0, 0.0, 1.0,
    
    
};

__device__ __constant__ int ffw_sg2_sphere_to_joint[124] = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    4,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    7,
    7,
    7,
    7,
    7,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    9,
    9,
    9,
    10,
    10,
    10,
    11,
    11,
    11,
    12,
    12,
    12,
    12,
    13,
    13,
    14,
    14,
    14,
    14,
    14,
    15,
    15,
    15,
    15,
    15,
    15,
    15,
    15,
    15,
    15,
    15,
    15,
    15,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
};

__device__ __constant__ int ffw_sg2_flattened_joint_to_spheres[140] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    -1,
    9,
    10,
    11,
    12,
    13,
    14,
    116,
    117,
    118,
    119,
    120,
    121,
    122,
    123,
    -1,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    -1,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    -1,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    -1,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    -1,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    -1,
    65,
    66,
    67,
    68,
    69,
    -1,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    -1,
    83,
    84,
    85,
    -1,
    86,
    87,
    88,
    -1,
    89,
    90,
    91,
    -1,
    92,
    93,
    94,
    95,
    -1,
    96,
    97,
    -1,
    98,
    99,
    100,
    101,
    102,
    -1,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    -1
};

__device__ __constant__ int ffw_sg2_joint_types[] = {
    3,
    2,
    4,
    3,
    5,
    4,
    5,
    4,
    3,
    4,
    3,
    5,
    4,
    5,
    4,
    3
};

__device__ __constant__ int ffw_sg2_self_cc_ranges[122][3] = {
    { 0, 15, 123 },
    { 1, 15, 123 },
    { 2, 15, 123 },
    { 3, 15, 123 },
    { 4, 15, 123 },
    { 5, 15, 123 },
    { 6, 15, 123 },
    { 7, 15, 123 },
    { 8, 15, 123 },
    { 9, 25, 82 },
    { 9, 86, 115 },
    { 10, 25, 82 },
    { 10, 86, 115 },
    { 11, 25, 82 },
    { 11, 86, 115 },
    { 12, 25, 82 },
    { 12, 86, 115 },
    { 13, 25, 82 },
    { 13, 86, 115 },
    { 14, 25, 82 },
    { 14, 86, 115 },
    { 15, 35, 123 },
    { 16, 35, 123 },
    { 17, 35, 123 },
    { 18, 35, 123 },
    { 19, 35, 123 },
    { 20, 35, 123 },
    { 21, 35, 123 },
    { 22, 35, 123 },
    { 23, 35, 123 },
    { 24, 35, 123 },
    { 25, 45, 123 },
    { 26, 45, 123 },
    { 27, 45, 123 },
    { 28, 45, 123 },
    { 29, 45, 123 },
    { 30, 45, 123 },
    { 31, 45, 123 },
    { 32, 45, 123 },
    { 33, 45, 123 },
    { 34, 45, 123 },
    { 35, 55, 123 },
    { 36, 55, 123 },
    { 37, 55, 123 },
    { 38, 55, 123 },
    { 39, 55, 123 },
    { 40, 55, 123 },
    { 41, 55, 123 },
    { 42, 55, 123 },
    { 43, 55, 123 },
    { 44, 55, 123 },
    { 45, 65, 123 },
    { 46, 65, 123 },
    { 47, 65, 123 },
    { 48, 65, 123 },
    { 49, 65, 123 },
    { 50, 65, 123 },
    { 51, 65, 123 },
    { 52, 65, 123 },
    { 53, 65, 123 },
    { 54, 65, 123 },
    { 55, 70, 123 },
    { 56, 70, 123 },
    { 57, 70, 123 },
    { 58, 70, 123 },
    { 59, 70, 123 },
    { 60, 70, 123 },
    { 61, 70, 123 },
    { 62, 70, 123 },
    { 63, 70, 123 },
    { 64, 70, 123 },
    { 65, 77, 123 },
    { 66, 77, 123 },
    { 67, 77, 123 },
    { 68, 77, 123 },
    { 69, 77, 123 },
    { 70, 83, 123 },
    { 71, 83, 123 },
    { 72, 83, 123 },
    { 73, 83, 123 },
    { 74, 83, 123 },
    { 75, 83, 123 },
    { 76, 83, 123 },
    { 77, 83, 123 },
    { 78, 83, 123 },
    { 79, 83, 123 },
    { 80, 83, 123 },
    { 81, 83, 123 },
    { 82, 83, 123 },
    { 83, 89, 123 },
    { 84, 89, 123 },
    { 85, 89, 123 },
    { 86, 92, 123 },
    { 87, 92, 123 },
    { 88, 92, 123 },
    { 89, 96, 123 },
    { 90, 96, 123 },
    { 91, 96, 123 },
    { 92, 98, 123 },
    { 93, 98, 123 },
    { 94, 98, 123 },
    { 95, 98, 123 },
    { 96, 103, 123 },
    { 97, 103, 123 },
    { 98, 110, 123 },
    { 99, 110, 123 },
    { 100, 110, 123 },
    { 101, 110, 123 },
    { 102, 110, 123 },
    { 103, 116, 123 },
    { 104, 116, 123 },
    { 105, 116, 123 },
    { 106, 116, 123 },
    { 107, 116, 123 },
    { 108, 116, 123 },
    { 109, 116, 123 },
    { 110, 116, 123 },
    { 111, 116, 123 },
    { 112, 116, 123 },
    { 113, 116, 123 },
    { 114, 116, 123 },
    { 115, 116, 123 }
};

__device__ __constant__ int ffw_sg2_joint_parents[16] = {
    0,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    1,
    9,
    10,
    11,
    12,
    13,
    14
};

__device__ __constant__ int ffw_sg2_T_memory_idx[16] = {
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
};

__device__ __constant__ int ffw_sg2_dfs_order[16] = {
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
};

__device__ __constant__ int ffw_sg2_joint_id_to_dof[16] = {
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
};

template <>
__device__ void fk<ppln::robots::FfwSg2>(
    const float* q,
    volatile float* sphere_pos, // 124 spheres x 16 robots x 3 coordinates (each column is a robot)
    float *T, // 16 robots x 2 x 4x4 transform matrix , column major
    const int tid
)
{
    // every 4 threads are responsible for one column of the transform matrix T
    // make_transform will calculate the necessary column of T_step needed for the thread
    const int col_ind = tid % 4;
    const int batch_ind = tid / 4;

    int T_offset = batch_ind * 2 * 16;
    float T_step_col[4]; // 4x1 column of the joint transform matrix for this thread
    float *T_base = T + T_offset; // 4x4 transform matrix for the batch
    
    #pragma unroll
    for (int i = 0; i < 2; ++i) {
        float *T_col_i = T_base + i * 16 + col_ind * 4;
        for (int r=0; r<4; r++) {
            T_col_i[r] = 0.0f;
        }
        T_col_i[col_ind] = 1.0f;
    }
    __syncthreads();

    int joint_to_sphere_ind = 0;

    for (int j = 0; j < FFW_SG2_JOINT_COUNT; ++j) {
        int i = ffw_sg2_dfs_order[j];
        float T_col_tmp[4];
        int parent_idx = ffw_sg2_joint_parents[i];
        int T_memory_idx_parent = ffw_sg2_T_memory_idx[parent_idx];
        int T_memory_idx = ffw_sg2_T_memory_idx[i];
        int q_idx = ffw_sg2_joint_id_to_dof[i];
        if (j > 0) {
            int ft_addr_start = i * 16;
            int joint_type = ffw_sg2_joint_types[i];

            if (joint_type <= FFW_SG2_Z_PRISM) {
                prism_fn(&ffw_sg2_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col, joint_type);
            }
            else if (joint_type == FFW_SG2_X_ROT) {
                xrot_fn(&ffw_sg2_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            else if (joint_type == FFW_SG2_Y_ROT) {
                yrot_fn(&ffw_sg2_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            else if (joint_type == FFW_SG2_Z_ROT) {
                zrot_fn(&ffw_sg2_fixed_transforms[ft_addr_start], q[q_idx], col_ind, T_step_col);
            }
            
            for (int r=0; r<4; r++){
                T_col_tmp[r] = dot4_col(&T_base[T_memory_idx_parent*16 + r], T_step_col);
            }
            for (int r=0; r<4; r++){
                T_base[T_memory_idx*16 + col_ind*4 + r] = T_col_tmp[r];
            }
        }
        __syncwarp();
        while (ffw_sg2_flattened_joint_to_spheres[joint_to_sphere_ind] != -1) {
            int sphere_ind = ffw_sg2_flattened_joint_to_spheres[joint_to_sphere_ind];
            if (col_ind < 3) {
                // sphere sphere_ind, robot batch_ind (FFW_SG2_BATCH_SIZE robots), coord col_ind
                sphere_pos[sphere_ind * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + col_ind] = 
                    T_base[T_memory_idx*16 + col_ind] * ffw_sg2_spheres_array[sphere_ind].x +
                    T_base[T_memory_idx*16 + col_ind + M] * ffw_sg2_spheres_array[sphere_ind].y +
                    T_base[T_memory_idx*16 + col_ind + M*2] * ffw_sg2_spheres_array[sphere_ind].z +
                    T_base[T_memory_idx*16 + col_ind + M*3];
            }
            joint_to_sphere_ind++;
        }
        joint_to_sphere_ind++;
        __syncthreads();
    }
}

// 4 threads per discretized motion for self-collision check
template <>
__device__ bool self_collision_check<ppln::robots::FfwSg2>(volatile float* sphere_pos, volatile int* joint_in_collision, const int tid){
    const int thread_ind = tid % 4;
    const int batch_ind = tid / 4;
    bool has_collision = false;

    for (int i = thread_ind; i < FFW_SG2_SELF_CC_RANGE_COUNT; i += 4) {
        if (warp_any_active_mask(has_collision)) return false;
        int sphere_1_ind = ffw_sg2_self_cc_ranges[i][0];
        if (joint_in_collision[FFW_SG2_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_sphere_to_joint[sphere_1_ind]] == 0) continue;
        float sphere_1[3] = {
            sphere_pos[sphere_1_ind * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 0],
            sphere_pos[sphere_1_ind * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 1],
            sphere_pos[sphere_1_ind * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 2]
        };
        for (int j = ffw_sg2_self_cc_ranges[i][1]; j <= ffw_sg2_self_cc_ranges[i][2]; j++) {
            float sphere_2[3] = {
                sphere_pos[j * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 0],
                sphere_pos[j * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 1],
                sphere_pos[j * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 2]
            };
            if (sphere_sphere_self_collision(
                sphere_1[0], sphere_1[1], sphere_1[2], ffw_sg2_spheres_array[sphere_1_ind].w,
                sphere_2[0], sphere_2[1], sphere_2[2], ffw_sg2_spheres_array[j].w
            )){
                //return false;
                has_collision=true;
            }
        }
    }
    return !has_collision;

}

__device__ __forceinline__
bool ffw_sg2_self_collision_check_early(
    volatile float *sphere_pos,
    volatile int *joint_in_collision,
    const int tid,
    volatile unsigned int *motion_cc_flag
) {
    const int thread_ind = tid % 4;
    const int batch_ind  = tid / 4;

    for (
        int i = thread_ind;
        i < FFW_SG2_SELF_CC_RANGE_COUNT;
        i += 4
    ) {
        // block의 다른 waypoint에서 collision 확정
        if (motion_cc_should_stop(motion_cc_flag)) {
            return false;
        }

        const int sphere_1_ind =
            ffw_sg2_self_cc_ranges[i][0];

        if (
            joint_in_collision[
                FFW_SG2_JOINT_FLAG_STRIDE * batch_ind +
                ffw_sg2_sphere_to_joint[sphere_1_ind]
            ] == 0
        ) {
            continue;
        }

        const float sphere_1[3] = {
            sphere_pos[
                sphere_1_ind *
                FFW_SG2_BATCH_SIZE * 3 +
                batch_ind * 3 + 0
            ],
            sphere_pos[
                sphere_1_ind *
                FFW_SG2_BATCH_SIZE * 3 +
                batch_ind * 3 + 1
            ],
            sphere_pos[
                sphere_1_ind *
                FFW_SG2_BATCH_SIZE * 3 +
                batch_ind * 3 + 2
            ]
        };


        for (
            int j = ffw_sg2_self_cc_ranges[i][1];
            j <= ffw_sg2_self_cc_ranges[i][2];
            ++j
        ) {
            // 다른 thread가 그 사이 실제 collision을 찾았을 수도 있음
            if (motion_cc_should_stop(motion_cc_flag)) {
                return false;
            }

            const float sphere_2[3] = {
                sphere_pos[
                    j * FFW_SG2_BATCH_SIZE * 3 +
                    batch_ind * 3 + 0
                ],
                sphere_pos[
                    j * FFW_SG2_BATCH_SIZE * 3 +
                    batch_ind * 3 + 1
                ],
                sphere_pos[
                    j * FFW_SG2_BATCH_SIZE * 3 +
                    batch_ind * 3 + 2
                ]
            };

            if (
                sphere_sphere_self_collision(
                    sphere_1[0],
                    sphere_1[1],
                    sphere_1[2],
                    ffw_sg2_spheres_array[
                        sphere_1_ind
                    ].w,

                    sphere_2[0],
                    sphere_2[1],
                    sphere_2[2],
                    ffw_sg2_spheres_array[j].w
                )
            ) {
                motion_cc_report_collision(
                    motion_cc_flag
                );

                return false;
            }
        }
    }

    return true;
}

// 4 threads per discretized motion for env collision check
template <>
__device__ bool env_collision_check<ppln::robots::FfwSg2>(volatile float* sphere_pos, volatile int* joint_in_collision, ppln::collision::Environment<float> *env, const int tid){
    const int thread_ind = tid % 4;
    const int batch_ind = tid / 4;
    bool has_collision=false;

    for (int i = thread_ind; i < FFW_SG2_SPHERE_COUNT-FFW_SG2_SPHERE_COUNT%4; i += 4){
        // sphere i, robot batch_ind (16 robots)
        if (joint_in_collision[FFW_SG2_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_sphere_to_joint[i]] > 0 && 
            sphere_environment_in_collision(
                env,
                sphere_pos[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 0],
                sphere_pos[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 1],
                sphere_pos[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 2],
                ffw_sg2_spheres_array[i].w
            )
        ) {
            //return false;
            has_collision=true;
        } 
        if (warp_any_full_mask(has_collision)) return false;
    }
    int i=FFW_SG2_SPHERE_COUNT-1-thread_ind;
    if (joint_in_collision[FFW_SG2_JOINT_FLAG_STRIDE * batch_ind + ffw_sg2_sphere_to_joint[i]] > 0 && 
        sphere_environment_in_collision(
            env,
            sphere_pos[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 0],
            sphere_pos[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 1],
            sphere_pos[i * FFW_SG2_BATCH_SIZE * 3 + batch_ind * 3 + 2],
            ffw_sg2_spheres_array[i].w
        )
    ) {
        return false;
    } 
    return true;
}

__device__ __forceinline__
bool ffw_sg2_env_collision_check_early(
    volatile float *sphere_pos,
    volatile int *joint_in_collision,
    ppln::collision::Environment<float> *env,
    const int tid,
    volatile unsigned int *motion_cc_flag
) {
    const int thread_ind = tid % 4;
    const int batch_ind  = tid / 4;

    // 기존 exact env collision과 같은 sphere 분배
    for (
        int i = thread_ind;
        i < FFW_SG2_SPHERE_COUNT - FFW_SG2_SPHERE_COUNT % 4;
        i += 4
    ) {
        // 다른 waypoint에서 이미 실제 collision 발견
        if (motion_cc_should_stop(motion_cc_flag)) {
            return false;
        }

        if (
            joint_in_collision[
                FFW_SG2_JOINT_FLAG_STRIDE * batch_ind +
                ffw_sg2_sphere_to_joint[i]
            ] > 0
            &&
            sphere_environment_in_collision(
                env,
                sphere_pos[
                    i * FFW_SG2_BATCH_SIZE * 3 +
                    batch_ind * 3 + 0
                ],
                sphere_pos[
                    i * FFW_SG2_BATCH_SIZE * 3 +
                    batch_ind * 3 + 1
                ],
                sphere_pos[
                    i * FFW_SG2_BATCH_SIZE * 3 +
                    batch_ind * 3 + 2
                ],
                ffw_sg2_spheres_array[i].w
            )
        ) {
            // 실제 collision 확정
            motion_cc_report_collision(
                motion_cc_flag
            );

            return false;
        }
    }


    // 기존 remainder sphere 처리
    const int i =
        FFW_SG2_SPHERE_COUNT - 1 - thread_ind;

    if (motion_cc_should_stop(motion_cc_flag)) {
        return false;
    }

    if (
        joint_in_collision[
            FFW_SG2_JOINT_FLAG_STRIDE * batch_ind +
            ffw_sg2_sphere_to_joint[i]
        ] > 0
        &&
        sphere_environment_in_collision(
            env,
            sphere_pos[
                i * FFW_SG2_BATCH_SIZE * 3 +
                batch_ind * 3 + 0
            ],
            sphere_pos[
                i * FFW_SG2_BATCH_SIZE * 3 +
                batch_ind * 3 + 1
            ],
            sphere_pos[
                i * FFW_SG2_BATCH_SIZE * 3 +
                batch_ind * 3 + 2
            ],
            ffw_sg2_spheres_array[i].w
        )
    ) {
        motion_cc_report_collision(
            motion_cc_flag
        );

        return false;
    }

    return true;
}
}
